import { DiGhostSmall } from "react-icons/di";
import {
   LuAlignHorizontalJustifyStart,
   LuAlignVerticalJustifyEnd,
} from "react-icons/lu";
import { RxSpaceEvenlyHorizontally } from "react-icons/rx";
import { ContainerConfig } from "../dataTypes";

export const containerConfig: ContainerConfig[] = [
   {
      key: "display",
      title: "Display",
      description: "Sets the display type",
      icon: DiGhostSmall,
      type: "select",
      options: ["grid", "block"],
      defaultValue: "grid",
   },
   {
      itemType: "dropdown",
      dropDownType: "iteration",
      placeholder: "Grid Column",
      key: "gridTemplateColumns",
      title: "Grid Template Columns",
      description: "Sets the columns of the grid",
      icon: LuAlignHorizontalJustifyStart,
      type: "input",
      inputType: "unit",
      unitOptions: ["fr", "px", "%"],
      defaultValue: "1fr 1fr",
   },
   {
      itemType: "dropdown",
      dropDownType: "iteration",
      placeholder: "Grid Row",
      key: "gridTemplateRows",
      title: "Grid Template Rows",
      description: "Sets the rows of the grid",
      icon: LuAlignVerticalJustifyEnd,
      type: "input",
      inputType: "unit",
      unitOptions: ["fr", "px", "%"],
      defaultValue: "1fr 1fr",
   },
   {
      itemType: "dropdown",
      dropDownType: "combine",
      combineData: [
         {
            key: "rowGap",
            title: "Row Gap",
            description: "Sets the gap between rows",
            type: "input",
            inputType: "unit",
            unitOptions: ["px", "%"],
         },
         {
            key: "columnGap",
            title: "Column Gap",
            description: "Sets the gap between columns",
            type: "input",
            inputType: "unit",
            unitOptions: ["px", "%"],
         },
      ],
      key: "gap",
      title: "Gap",
      description: "Sets gap between items",
      icon: RxSpaceEvenlyHorizontally,
      type: "input",
      inputType: "unit",
      unitOptions: ["px", "%"],
      defaultValue: "10px 10px",
   },
   {
      key: "justifyItems",
      title: "Justify Items",
      description: "Sets the alignment of items on the main axis",
      icon: LuAlignHorizontalJustifyStart,
      type: "select",
      options: ["stretch", "start", "center", "end"],
      defaultValue: "stretch",
   },
   {
      key: "alignItems",
      title: "Align Items",
      description: "Sets the alignment of items on the cross axis",
      icon: LuAlignVerticalJustifyEnd,
      type: "select",
      options: ["stretch", "start", "center", "end"],
      defaultValue: "stretch",
   },
   {
      key: "justifyContent",
      title: "Justify Content",
      description: "Sets the alignment of items on the main axis",
      icon: LuAlignHorizontalJustifyStart,
      type: "select",
      options: [
         "start",
         "center",
         "end",
         "space-around",
         "space-between",
         "space-evenly",
      ],
      defaultValue: "start",
   },
   {
      key: "alignContent",
      title: "Align Content",
      description: "Sets the alignment of items on the cross axis",
      icon: LuAlignVerticalJustifyEnd,
      type: "select",
      options: [
         "start",
         "center",
         "end",
         "space-around",
         "space-between",
         "space-evenly",
      ],
      defaultValue: "start",
   },
   {
      key: "gridAutoColumns",
      title: "Grid Auto Columns",
      description: "Sets the size of the columns that are not defined",
      icon: LuAlignHorizontalJustifyStart,
      type: "input",
      inputType: "unit",
      unitOptions: ["auto", "fr", "px", "%"],
      defaultValue: "auto",
   },
   {
      key: "gridAutoRows",
      title: "Grid Auto Rows",
      description: "Sets the size of the rows that are not defined",
      icon: LuAlignVerticalJustifyEnd,
      type: "input",
      inputType: "unit",
      unitOptions: ["auto", "fr", "px", "%"],
      defaultValue: "auto",
   },
   {
      key: "gridAutoFlow",
      title: "Grid Auto Flow",
      description: "Controls the auto placement of items",
      icon: DiGhostSmall,
      type: "select",
      options: ["row", "column", "row dense", "column dense"],
      defaultValue: "row",
   },
];
